PrototipoMINVU/Controllers/ControlController.cs
using CapaDatosBO;
using CapaDatosNEGOCIO;
using Rotativa;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PrototipoMINVU.Controllers
{
    public class ControlController : Controller
    {
        // ---------------------------FUNCIONES PARA EL RETORNO DE VISTAS

        public ActionResult ControlSistemas()
        {
            var alerta = Session["UsuarioConfirmado"];
            if (alerta != null)
            {
                return View();
            }
            else
                return RedirectToAction("Login", "Seguridad");
        }

        public ActionResult ReporteSistemas()
        {
            var alerta = Session["UsuarioConfirmado"];
            if (alerta != null)
            {
                Models.Registro cargador = new Models.Registro();

                cargador.CargaModulos();
                cargador.CargaSistemas();
                return View(cargador);
            }
            else
                return RedirectToAction("Login", "Seguridad");
        }

  

        // ---------------------FUNCIONES BACKEND PARA EL FUNCIONAMIENTO DEL SISTEMA.
        public ActionResult GenerarPDFModulo(int id_reportemodulo)
        {
            // Establece el nombre de la vista que deseas convertir en PDF
            string reporteVista = "pdfModulo";

            // Se crea un modelo que contenga los datos que se envian a la vista
            
            Models.Registro cargador = new Models.Registro();
            cargador.id_reportesistema = id_reportemodulo; 
            cargador.CargaModulobyID(id_reportemodulo);
            cargador.CargaIntegraciones();

            cargador.GenerarReporteModulo(id_reportemodulo);



            // Genera la vista como un PDF
            var pdf = new ViewAsPdf(reporteVista, cargador)
            {
                // Configura opciones adicionales aquí
                FileName = "ReportePrototipo.pdf",
                PageSize = Rotativa.Options.Size.Folio,
                PageMargins = new Rotativa.Options.Margins(5, 10, 5, 10)
            };

            // Convierte el PDF en un array de bytes
            byte[] pdfData = pdf.BuildFile(ControllerContext);

            // Establece el tipo MIME para que el navegador muestre el PDF
            Response.AddHeader("Content-Disposition", "inline; filename=ReportePrototipo.pdf");

            // Devuelve el PDF como un FileResult
            return File(pdfData, "application/pdf");
        }

        public ActionResult GenerarPDFSistema(int id_reportesistema)
        {
            // Establece el nombre de la vista que deseas convertir en PDF
            string reporteVista = "pdfSistemas";

            // Se crea un modelo que contenga los datos que se envian a la vista

            Models.Registro cargador = new Models.Registro();
            cargador.id_reportesistema = id_reportesistema;

            cargador.CargaSistemabyID(id_reportesistema);
            cargador.CargaIntegracionesby(id_reportesistema);



            // Genera la vista como un PDF
            var pdf = new ViewAsPdf(reporteVista, cargador)
            {
                // Configura opciones adicionales aquí
                FileName = "ReportePrototipo.pdf",
                PageSize = Rotativa.Options.Size.Folio,
                PageMargins = new Rotativa.Options.Margins(5, 10, 5, 10)
            };

            // Convierte el PDF en un array de bytes
            byte[] pdfData = pdf.BuildFile(ControllerContext);

            // Establece el tipo MIME para que el navegador muestre el PDF
            Response.AddHeader("Content-Disposition", "inline; filename=ReportePrototipo.pdf");

            // Devuelve el PDF como un FileResult
            return File(pdfData, "application/pdf");
        }






        // CONTROL PARA LOS SISTEMAS Y SUS CARACTERISTICAS.

        [HttpGet]
        public JsonResult ReporteSISTEMAXVARIABLE(string control_select)
        {
            SistemasBUSINESS cargador = new SistemasBUSINESS();
            List<ReporteGeneralBO> objLista = new List<ReporteGeneralBO>();

            objLista = cargador.ReporteSISTEMAXVARIABLE(control_select);

            return Json(objLista, JsonRequestBehavior.AllowGet);
        }


        // CONTROL PARA LOS MODULOS (Caracteristicas generales, depende del parámetro "control_select")

        [HttpGet]
        public JsonResult ReporteMODULOXVARIABLE(string control_select)
        {
            SistemasBUSINESS cargador = new SistemasBUSINESS();
            List<ReporteGeneralBO> objLista = new List<ReporteGeneralBO>();

            objLista = cargador.ReporteSUBSISTEMAXVARIABLE(control_select);

            return Json(objLista, JsonRequestBehavior.AllowGet);
        }



        // CONTROL PARA LAS INTEGRACIONES

        [HttpGet]
        public JsonResult ReporteINTEEX()
        {
            SistemasBUSINESS cargador = new SistemasBUSINESS();
            List<ReporteGeneralBO> objLista = new List<ReporteGeneralBO>();
           
            objLista= cargador.ReporteINTEEX();

            return Json(objLista, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult ReporteINTEIN()
        {
            SistemasBUSINESS cargador = new SistemasBUSINESS();
            List<ReporteGeneralBO> objLista = new List<ReporteGeneralBO>();
            objLista = cargador.ReporteINTEIN();      
            
            return Json(objLista, JsonRequestBehavior.AllowGet);
        }

















       


    }
}

PrototipoMINVU/Views/Control/ReportePDF.cshtml
@model PrototipoMINVU.Models.Registro
@{
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>



    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prototipo Sistemas - MINVU</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
    <link href="../css/app.css" rel="stylesheet">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


</head>

<body>
    <div class="container">

        <div class="row">
            <div class="col-4" style="font-size:smaller; margin-left:25px">
                <div class="row">
                    <div class="form-group row">
                        <img width="100" height="220" src="~/img/logos9.png" />
                    </div>

                </div>
            </div>
            <div class="col-4" style="position:absolute; top:2px; left:600px">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for=" establecimientoOrigen" class="card-title text-blac-900" style="font-size: 14px">Fecha Solicitud: </label>
                            <label class="card-text" style="font-size: 14px"> </label>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-4" style="position:absolute; top:2px; left:310px">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for=" establecimientoOrigen" class="card-title text-blac-900" style="font-size: 14px">Código Reporte: </label>
                            <label class="card-text" style="font-size: 14px"> </label>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="container" style="border:1px solid black">

        <div class="row">

            <div class="row" style="margin-left:0px">
                <div class="col-lg-6">
                    <div class="card shadow">
                        <div class="font_calibri">
                            <h3 style="text-align: center">Reporte General de Control de los Sistemas del MINVU</h3>
                            <hr style="border: 1px solid black" />

                            En este reporte se puede visualizar el nombre, el estado y el ambiente del sistema.
                            También se muestran los primeros 5 subsistemas que están enlazados principalmente a este sistema.
                            Se destaca, que las caracteristicas y/o datos escogidos para este prototipo, son a
                            modo de prueba según las límitaciones del proyecto.<br />

                            Esta interfaz es un ejemplo del prototipo a modo de imagen.<br /><br />
                            Universidad Tecnológica Metropolitana.<br />
                            <b>Profesor Guía:</b> Yelka Ruiz.<br /><br />
                            <b>Rodrigo Álvarez.</b>


                        </div>
                    </div>
                </div>



            </div>

            <hr />


            <div class="font_registro">
                <div class="col-12">

                    <div class="col-12" style="">
                        <label>Nombre del Sistema:</label>
                        <p style="text-align:center">@Model.SistemaExample.NombreSistema</p>
                    </div>
                    <hr style="border: 1px solid black" />

                    <div class="col-12" style="">
                        <label> Estado del Sistema: </label>
                        <p style="text-align:center"> @Model.SistemaExample.DescripcionEstado</p>
                    </div>
                    <hr style="border: 1px solid black" />

                    <div class="col-12" style="">
                        <label> Ambiente Alojado: </label>

                        <p style="text-align:center"> @Model.SistemaExample.AmbienteAlojado</p>
                    </div>
                    <hr style="border: 1px solid black" />

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <b>
                    <label>
                        Lista de Sub Sistemas del sistema @Model.SistemaExample.NombreSistema :
                    </label>
                </b>
            </div>

        </div>

        <table align="center" border="1" style="width:contain; height:contain;" class="table table-bordered table-hover table-condensed table-striped shadow-lg bg-white position-static" id="datatableReg">
            <thead>
                <tr>
                    <th>N° Sistema</th>
                    <th>Nombre Sistema</th>
                    <th>Jefe proyecto</th>
                    <th>Estado Sistema</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListaSubSistemas != null)
                {
                    int aux = 1;
                    foreach (var item in Model.ListaSubSistemas)
                    {
                        if (aux <= 5)
                        {
                            <tr>
                                <td class="id">@aux</td>
                                <td>@item.NombreSubSistema</td>
                                <td>@item.NombreJefeProyecto</td>
                                <td>@item.EstadoSubSistema</td>
                            </tr>
                        }

                        aux++;
                    }
                }
            </tbody>
        </table>
    </div>

</body>
</html>

PrototipoMINVU/Views/Control/ReporteSistemas.cshtml
@model PrototipoMINVU.Models.Registro


<div class="container-fluid">
    <div class="bg-gradient-primary py-3 shadow-sm">
        <div class="card">
            <div class="card shadow">
                <div class="container-fluid">

                    <div class="row">
                        <div class="font_registro">
                            <h2>Reportes de sistemas.</h2>
                            <hr />
                        </div>
                    </div>

                    <div class="row" id="textindexregistro">
                        <div class="col-lg-12">
                            <div class="card shadow">
                                <div class="font_registro">
                                    En esta pantalla se podrá obtener el reporte de los sistemas generales de la base de datos del prototipo.
                                    Aqui se podrán visualizar, descargar e imprimir los reportes que representan la situación de los sistemas actual
                                    para tener en papel la información.<br /><br />

                                    Se destaca, que las caracteristicas y/o datos de prueba escogidos para este prototipo y los reportes, son a
                                    modo de prueba según las límitaciones del proyecto.<br />

                                    Universidad Tecnológica Metropolitana.<br />

                                    <b>Profesor Guía:</b> Yelka Ruiz.<br />
                                    <b>Rodrigo Álvarez.</b>
                                </div>
                            </div>
                        </div>
                    </div>

                    <hr />

                    <div class="row">
                        <div class="col-lg-4" style="text-align:end;">
                            <b>@Html.LabelFor(m => m.id_reportemodulo, "Seleccione Modulo a Reportar:")</b>
                        </div>
                        <div class="col-lg-3">
                            @Html.DropDownListFor(m => m.id_reportemodulo, new SelectList(Model.ListaModulos, "idSistema", "NombreSistema"), "Seleccione Modulo", new { @class = "form-select", @id = "id_reportemodulo" })
                        </div>
                        <div class="col-lg-2">
                            <input type="button" id="generarPDFModulo" value="Generar PDF" />
                        </div>

                    </div>
                    <hr />

                    <div class="row">
                        <div class="col-lg-4" style="text-align:end;">
                            <b>@Html.LabelFor(m => m.id_reportesistema, "Seleccione Sistema a Reportar:")</b>
                        </div>
                        <div class="col-lg-3">
                            @Html.DropDownListFor(m => m.id_reportesistema, new SelectList(Model.ListaSistemas, "id_sistema", "NombreSistema"), "Seleccione Sistema", new { @class = "form-select", @id = "id_reportesistema" })
                        </div>
                        <div class="col-lg-2">
                            <input type="button" id="generarPDFSistemas" value="Generar PDF" />
                        </div>


                    </div>

                    <hr />
                </div>

            </div>
        </div>
    </div>
</div>


<footer class="footer">
    <div class="container-fluid">
        <div class="row text-muted">
            <div class="col-6 text-start">
                <p class="mb-0">
                    <a class="text-muted"> <span>Copyright &copy; Universidad Tecnológica Metropolitana - Facultad Ingenieria</span></a>								&copy;
                </p>
            </div>
            <div class="col-6 text-end">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        <a class="text-muted" href="https://www.minvu.gob.cl/beneficios/vivienda/" target="_blank">Vivienda</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="https://www.minvu.gob.cl/noticias/" target="_blank">Noticia</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="https://www.minvu.gob.cl/sobre-minvu/" target="_blank">Sobre MINVU</a>
                    </li>
                    <li class="list-inline-item">
                        <a class="text-muted" href="https://www.minvu.gob.cl/preguntas-frecuentes/" target="_blank">Preguntas Frecuentes</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>



<script>

    $("#generarPDFSistemas").click(function () {
        // Obtiene el valor seleccionado en el DropDownList
        var id_reportesistema = $("#id_reportesistema").val();

        // Asigna el valor al atributo data-id del botón
        $(this).data('id_reportesistema', id_reportesistema);

        // Abre la nueva ventana o pestaña con el valor actualizado
        window.open('@Url.Action("GenerarPDFSistema", "Control")?id_reportesistema=' + id_reportesistema, '_blank');
    });

    $("#generarPDFModulo").click(function () {
        // Obtiene el valor seleccionado en el DropDownList
        var id_reportemodulo = $("#id_reportemodulo").val();

        // Asigna el valor al atributo data-id del botón
        $(this).data('id_reportemodulo', id_reportemodulo);

        // Abre la nueva ventana o pestaña con el valor actualizado
        window.open('@Url.Action("GenerarPDFModulo", "Control")?id_reportemodulo=' + id_reportemodulo, '_blank');
    });




</script>

PrototipoMINVU/Views/Control/pdfModulo.cshtml
@model PrototipoMINVU.Models.Registro
@{
    Layout = null;
}
<!DOCTYPE html>

<html>

<head>



    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prototipo Sistemas - MINVU</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
    <link href="../css/app.css" rel="stylesheet">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


</head>

<body>
    <div class="container">

        <div class="row">
            <div class="col-4" style="font-size:smaller; margin-left:25px">
                <div class="row">
                    <div class="form-group row">
                        <img width="100" height="220" src="~/img/logos9.png" />
                    </div>

                </div>
            </div>
            <div class="col-4" style="position:absolute; top:2px; left:600px">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for=" establecimientoOrigen" class="card-title text-blac-900" style="font-size: 14px">Fecha Solicitud: </label>
                            <label class="card-text" style="font-size: 14px"> </label>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-4" style="position:absolute; top:2px; left:310px">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group row">
                            <label for=" establecimientoOrigen" class="card-title text-blac-900" style="font-size: 14px">Código Reporte: </label>
                            <label class="card-text" style="font-size: 14px"> </label>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="container" style="border:1px solid black">

        <div class="row">

            <div class="row" style="margin-left:0px">
                <div class="col-lg-6">
                    <div class="card shadow">
                        <div class="font_calibri">
                            <h3 style="text-align: center">Reporte General de Control de los Módulos del MINVU</h3>
                            <hr style="border: 1px solid black" />

                            En este reporte se puede visualizar el nombre, el estado y el ambiente de los modulos de sistemas.                            
                            Se destaca, que las caracteristicas y/o datos escogidos para este prototipo, son a
                            modo de prueba según las límitaciones del proyecto.<br />

                            Esta interfaz es un ejemplo del prototipo a modo de imagen.<br /><br />
                            Universidad Tecnológica Metropolitana.<br />
                            <b>Profesor Guía:</b> Yelka Ruiz.<br /><br />
                            <b>Rodrigo Álvarez.</b>


                        </div>
                    </div>
                </div>



            </div>

            <hr />


            <div class="font_registro">
                <div class="col-12">

                    <div class="col-12" style="">
                        <label>Nombre del Sistema:</label>
                        <p style="text-align:center">@Model.ModuloExample.NombreSistema</p>
                    </div>
                    <hr style="border: 1px solid black" />

                    <div class="col-12" style="">
                        <label>Descripción del Modulo:</label>
                        <p style="text-align:center">@Model.ModuloExample.descripcion</p>
                    </div>
                    <hr style="border: 1px solid black" />

                    <div class="col-12" style="">
                        <label> Estado del Sistema: </label>
                        <p style="text-align:center"> @Model.ModuloExample.DescripcionEstado</p>
                    </div>
                    <hr style="border: 1px solid black" />

                    <div class="col-12" style="">
                        <label> Ambiente Alojado: </label>

                        <p style="text-align:center"> @Model.ModuloExample.AmbienteAlojado</p>
                    </div>
                    <hr style="border: 1px solid black" />

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <b>
                    <label>
                        Lista de Integraciones del Modulo @Model.ModuloExample.NombreSistema :
                    </label>
                </b>
            </div>

        </div>

        <table align="center" border="1" style="width:contain; height:contain;" class="table table-bordered table-hover table-condensed table-striped shadow-lg bg-white position-static" id="datatableReg">
            <thead>
                <tr>
                    <th>N° integracion</th>
                    <th>Nombre Origen</th>
                    <th>Nombre Destino</th>
                    <th>Tipo Integracion</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ListaSistemas != null)
                {
                    int aux = 1;
                    foreach (var item in Model.ListaSistemas)
                    {
                        if (aux <= 5)
                        {
                            <tr>
                                <td class="id">@aux</td>
                                <td>@item.NombreSistema</td>
                                <td>@item.NombreJefeProyecto</td>
                                <td>@item.EstadoSistema</td>
                            </tr>
                        }

                        aux++;
                    }
                }
            </tbody>
        </table>
    </div>

</body>
</html>